<?php

$title = 'Добавить новую запись';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
  <a href="<?= $this->url('note') ?>">К списку записей</a>
</p>
<?php

$nickname = $form->get('nickname');
$nickname->setAttribute('class', 'form-control');
$nickname->setAttribute('placeholder', 'Никнейм пользователя');

$msg = $form->get('msg');
$msg->setAttribute('class', 'form-control');
$msg->setAttribute('placeholder', 'Сообщение');

$file = $form->get('file');
$file->setAttribute('class', 'form-control');
$file->setAttribute('placeholder', 'Картинка');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('note', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>

<div class="form-group nickname">
  <?= $this->formLabel($nickname) ?>
  <?= $this->formElement($nickname) ?>
  <?= $this->formElementErrors()->render($nickname, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
  <?= $this->formLabel($msg) ?>
  <?= $this->formElement($msg) ?>
  <?= $this->formElementErrors()->render($msg, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
  <?= $this->formLabel($form->get('file')); ?>
  <?= $this->formElement($form->get('file')); ?>
  <?= $this->formElementErrors($form->get('file')); ?> 
  <div class="hint">(Разрешены PNG и JPG форматы)</div>
  <img width=100 height=100 id="img" style="display: none" />
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();

?>

<script>
  document.getElementById("file").addEventListener('change', (e) => {
    const input = e.target;
    if (input.files && input.files[0]) {
      const reader = new FileReader();
      reader.onload = (e) => {
        const img = document.getElementById("img");
        img.src = e.target.result;
        img.style.display = 'block';
      }
      reader.readAsDataURL(input.files[0]);
    }
  });
</script>

<style>
  .nickname {
    max-width: 300px;
  }
</style>