<?php

$title = 'Редактирование записи';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
  <a href="<?= $this->url('note') ?>">К списку записей</a>
</p>
<?php

$nickname = $form->get('nickname');
$nickname->setAttribute('class', 'form-control');
$nickname->setAttribute('placeholder', 'Никнейм пользователя');

$msg = $form->get('msg');
$msg->setAttribute('class', 'form-control');
$msg->setAttribute('placeholder', 'Сообщение');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('note', ['action' => 'edit', 'id' => $id]));
$form->prepare();

echo $this->form()->openTag($form);
?>

<div class="form-group">
    <?= $this->formLabel($nickname) ?>
    <?= $this->formElement($nickname) ?>
    <?= $this->formElementErrors()->render($nickname, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($msg) ?>
    <?= $this->formElement($msg) ?>
    <?= $this->formElementErrors()->render($msg, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();

?>
